import React from 'react'
import Link from 'next/link'
import Head from 'next/head'
import Otherhero from './components/Otherhero'
import Navtip from './components/Navtip'
import Navbars from './components/Navbar'
import Projects from './components/Projects'
import Sectioncontact from './components/Sectioncontact'
import Footer from './components/Footer'
import Project1 from '../public/dauntless.png'
import Project2 from '../public/lms-system.jpg'
import Project3 from '../public/finance.jpg'

export default function Services() {
    return (
        <>
            <Head>
                <title>Perfcreg || Services Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Navtip />
                <Navbars />
                <Otherhero title="Portfolio" />

                <section className='section-projects'>
                    <div className="container">
                        <h4 className="tag">our successful projects</h4>
                        <h2 className='title mb-4'>And our clients love us for this.</h2>

                        <div className="row mt-4">

                            <div className="col-md-4">
                                <Projects url="https://www.dauntless.trade"
                                    title="Dauntless GC" 
                                    tag="Mobile App Dev"
                                    img={Project1.src}
                                    date="25th July, 2022" />
                            </div>


                            <div className="col-md-4">
                                <Projects url="#"
                                    title="Perfcreg eLearning"
                                    tag="LMS System"
                                    img={Project2.src}
                                    date="In Progress" />
                            </div>

                            <div className="col-md-4">
                                <Projects url="#"
                                    title="Perfcreg Fintech"
                                    tag="Web Development"
                                    img={Project3.src}
                                    date="15 Nov, 2022" />
                            </div>
                        </div>

                    </div>
                </section>


                <Sectioncontact />
                <Footer />
            </main>
        </>
    )
}
