import React from 'react'
import Link from 'next/link'
import Head from 'next/head'
import Otherhero from './components/Otherhero'
import Navtip from './components/Navtip'
import Navbars from './components/Navbar'
import Projects from './components/Projects'
import Sectioncontact from './components/Sectioncontact'
import Footer from './components/Footer'
import Project1 from '../public/dauntless.png'
import Project2 from '../public/lms-system.jpg'
import Project3 from '../public/finance.jpg'

export default function Services() {
    const data = [
        {
            "url": "http://www.dauntless.trade",
            title: "Dauntless GC",
            tag: "Mobile application",
            img: Project1.src,
            date: "25th July, 2022"
        },
        {
            url: "#",
            title: "AI e-Learning Platform",
            tag: "LMS System",
            img: Project2.src,
            date: "In Progress"
        },
        {
            url: "https://l9hha3dxz1.execute-api.eu-west-2.amazonaws.com/production/tc-backend/docs",
            title: "Thrift System Api",
            tag: "IOT",
            img: Project3.src,
            date: "15 Nov, 2022"
        }

    ]

    const [project, setProgect] = React.useState(data)
    return (
        <>
            <Head>
                <title>Perfcreg || Services Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Navtip />
                <Navbars />
                <Otherhero title="Portfolio" />

                <section className='section-projects'>
                    <div className="container">
                        <h4 className="tag">our successful projects</h4>
                        <h2 className='title mb-4'>And our clients love us for this.</h2>

                        <div className="row mt-4">
                        {
                        project.length > 0 && project.map((data, index) => (
                            <div className="col-md-4" key={data.date}>
                                <Projects url={data.url}
                                    title={data.title}
                                    tag={data.tag}
                                    img={data.img}
                                    date={data.date} />
                            </div>
                        ))}
                        </div>

                    </div>
                </section>


                <Sectioncontact />
                <Footer />
            </main>
        </>
    )
}
