import React from 'react'
import Head from 'next/head'
import Otherhero from './components/Otherhero'
import Navtip from './components/Navtip'
import Navbars from './components/Navbar'
import Sectioncontact from './components/Sectioncontact'
import Footer from './components/Footer'
import Project1 from '../public/images/project1.jpg'
import Project2 from '../public/images/project2.jpg'
import Project3 from '../public/images/project3.jpg'

export default function Services() {
    return (
        <>
            <Head>
                <title>Perfcreg || Services Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Navtip />
                <Navbars />
                <Otherhero title="Portfolio" />

                <section className='section-projects'>
                    <div className="container">
                        <h4 className="tag">our successful projects</h4>
                        <h2 className='title mb-4'>Lorem ipsum dolor sit amet consectetur.</h2>

                        <div className="row mt-4">
                            <div className="col-md-4">
                                <div className="project">
                                    <img src={Project1.src} className="project-img" />
                                    <div className="project-details">
                                        <span className="tag">23 July, 2022</span>

                                        <div className="info">
                                            <h1>Dauntless GC</h1>
                                            <p>Mobile App</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div className="col-md-4">
                                <div className="project">
                                    <img src={Project2.src} className="project-img" />
                                    <div className="project-details">
                                        <span className="tag">23 July, 2022</span>

                                        <div className="info">
                                            <h1>Dauntless GC</h1>
                                            <p>Mobile App</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div className="col-md-4">
                                <div className="project">
                                    <img src={Project3.src} className="project-img" />
                                    <div className="project-details">
                                        <span className="tag">23 July, 2022</span>

                                        <div className="info">
                                            <h1>Dauntless GC</h1>
                                            <p>Mobile App</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div className="col-md-4">
                                <div className="project">
                                    <img src={Project2.src} className="project-img" />
                                    <div className="project-details">
                                        <span className="tag">23 July, 2022</span>

                                        <div className="info">
                                            <h1>Dauntless GC</h1>
                                            <p>Mobile App</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div className="col-md-4">
                                <div className="project">
                                    <img src={Project1.src} className="project-img" />
                                    <div className="project-details">
                                        <span className="tag">23 July, 2022</span>

                                        <div className="info">
                                            <h1>Dauntless GC</h1>
                                            <p>Mobile App</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </section>


                <Sectioncontact />
                <Footer />
            </main>
        </>
    )
}
